// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProfileV2Test.FeatureFiles._5
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("5.5 To fill in block \"Skills\"", Description="\tIn order to inform employer\r\n\tAs authorized user\r\n\tI should have possibility to " +
        "fill in block \"Skills\"", SourceFile="FeatureFiles\\_5\\5.5 To fill block Skills.feature", SourceLine=4)]
    public partial class _5_5ToFillInBlockSkillsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "5.5 To fill block Skills.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "5.5 To fill in block \"Skills\"", "\tIn order to inform employer\r\n\tAs authorized user\r\n\tI should have possibility to " +
                    "fill in block \"Skills\"", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student checking resume block title of page", SourceLine=9)]
        public virtual void StudentCheckingResumeBlockTitleOfPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student checking resume block title of page", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("As unauthorised user I come to landing page of Profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.And("I log in as Vlad Davies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I open my personal menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I select button \"Resume\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I go to block \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.Then("I see resume block title \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("I see notification \"Mandatory field\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I see that tab name \"Skills\" is active", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student saves information", SourceLine=19)]
        public virtual void StudentSavesInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student saves information", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I filled all fields in \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.When("I press \"NEXT\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.And("I press \"BACK\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.Then("I can see data \"Skills\" is present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student can Check \"Skills\" block on error", SourceLine=25)]
        public virtual void StudentCanCheckSkillsBlockOnError()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student can Check \"Skills\" block on error", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I leave block \"Skills\" empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.When("I press \"NEXT\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.Then("Text field \"Skills\" is encircled red", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
 testRunner.And("I stay in block \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student deletes skills", SourceLine=31)]
        public virtual void StudentDeletesSkills()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student deletes skills", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("I wrote skills in field \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.When("I press cross near skill", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("This skill is deleted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void StudentCanSearchSkills(string option, string letter, string skills, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student can search skills", exampleTags);
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I type word for skills", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
 testRunner.When(string.Format("I enter \"{0}\" in field \"Skills\"", letter), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.Then(string.Format("I can see \"{0}\" starting from this letter in database", skills), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student can search skills, option1", SourceLine=42)]
        public virtual void StudentCanSearchSkills_Option1()
        {
#line 37
this.StudentCanSearchSkills("option1", "f", "Figma, Flask, Flux, Frameworks", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student can search skills, option2", SourceLine=42)]
        public virtual void StudentCanSearchSkills_Option2()
        {
#line 37
this.StudentCanSearchSkills("option2", "h", "Hibernate, HSQLDB, HTML, Hyper-V", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student can search skills, option3", SourceLine=42)]
        public virtual void StudentCanSearchSkills_Option3()
        {
#line 37
this.StudentCanSearchSkills("option3", "i", "IDEA, Injection, Interaction design", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student check language filter", SourceLine=46)]
        public virtual void StudentCheckLanguageFilter()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student check language filter", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.When("I write \"Абв\" in field \"Summary\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("I see the written \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void StudentChecksDefaultSkills(string stream, string defaultSkills, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Student Checks default skills", exampleTags);
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("As unauthorised user I come to landing page of Profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.And("I log in as student", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I open my personal menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("I select button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("For the first time I go to block \"Skills\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("My stream is <\"stream\">", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then(string.Format("I can see \"{0}\" default skills", defaultSkills), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Android Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_AndroidDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("Android Developer", "Java Core, Android SDK, RxJava, RxAndroid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Java Automated Testing", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_JavaAutomatedTesting()
        {
#line 61
this.StudentChecksDefaultSkills("Java Automated Testing", "Java, Selenium Webdriver, XML, HTML, CSS", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Business Analyst", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_BusinessAnalyst()
        {
#line 61
this.StudentChecksDefaultSkills("Business Analyst", "Analyzing Requirements, Vision&Scope, BPMN", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, C++ Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_CDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("C++ Developer", "С++, Qt Framework, STL", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Front-end Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_Front_EndDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("Front-end Developer", "HTML, CSS, JavaScript,  jQuery", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Java Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_JavaDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("Java Developer", "Java Core, Servlets, Spring", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, ASP.NET Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_ASP_NETDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("ASP.NET Developer", "С#, ASP.NET MVC,SOLID", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, IOS Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_IOSDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("IOS Developer", "Swift, SOLID, Xcode", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, PHP Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_PHPDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("PHP Developer", "PHP, Symfony, MySQL", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Python Developer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_PythonDeveloper()
        {
#line 61
this.StudentChecksDefaultSkills("Python Developer", "Python, Django, UnitTest", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Python Automated Testing", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_PythonAutomatedTesting()
        {
#line 61
this.StudentChecksDefaultSkills("Python Automated Testing", "Python, Linux, Automation", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, Software Testing", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_SoftwareTesting()
        {
#line 61
this.StudentChecksDefaultSkills("Software Testing", "Functional testing, TestRail, Jira", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Student Checks default skills, UI/UX Designer", SourceLine=70)]
        public virtual void StudentChecksDefaultSkills_UIUXDesigner()
        {
#line 61
this.StudentChecksDefaultSkills("UI/UX Designer", "Adobe Photoshop, Adobe Illustrator, Axure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
