#error (1:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background Fill in resume:'
#error (2:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given As unauthorised user I come to landing page of Profile'
#error (3:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I log in as Student # Data of users.feature'
#error (4:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I open my personal menu'
#error (5:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I start filling in my resume'
#error (7:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background common:'
#error (8:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given As unauthorised user I come to landing page of Profile'
#error (9:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I log in as Student #Data of users.feature'
#error (10:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I open my personal menu'
#error (12:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background HR:'
#error (13:1): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given As unauthorised user I come to landing page of Profile'