// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProfileV2Test.FeatureFiles._1
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("1.1 Landing page", Description="  In order to understand the value of the service\r\n  As unauthorized user\r\n  I wa" +
        "nt to see information about system", SourceFile="FeatureFiles\\_1\\1.1 Landing page.feature", SourceLine=2)]
    public partial class _1_1LandingPageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "1.1 Landing page.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "1.1 Landing page", "  In order to understand the value of the service\r\n  As unauthorized user\r\n  I wa" +
                    "nt to see information about system", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
  #line 9
    testRunner.Given("As unauthorised user I come to landing page of Profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verification text fields", SourceLine=10)]
        public virtual void VerificationTextFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verification text fields", ((string[])(null)));
#line 11
  this.ScenarioSetup(scenarioInfo);
#line 8
  this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "text"});
            table1.AddRow(new string[] {
                        "Уважаемые выпускники!"});
            table1.AddRow(new string[] {
                        "Данное приложение – это Ваш помощник в составлении резюме."});
            table1.AddRow(new string[] {
                        "При заполнении CV помните:"});
            table1.AddRow(new string[] {
                        "- Заполнять информацию необходимо на английском языке,"});
            table1.AddRow(new string[] {
                        "- Воспользуйтесь рекомендациями по составлению резюме,"});
            table1.AddRow(new string[] {
                        "- Не пропускайте блоки."});
            table1.AddRow(new string[] {
                        ""});
            table1.AddRow(new string[] {
                        "После заполнения не забудьте сохранить Ваше CV и информировать об этом HR."});
            table1.AddRow(new string[] {
                        "При появлении вопросов пишите: Hr@it-academy.by"});
#line 12
    testRunner.Then("I see welcome text", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verification input fields", SourceLine=23)]
        public virtual void VerificationInputFields()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verification input fields", ((string[])(null)));
#line 24
  this.ScenarioSetup(scenarioInfo);
#line 8
  this.FeatureBackground();
#line 25
    testRunner.Then("I see input field with Input placeholder \"e-mail\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
    testRunner.And("I see input field with Input placeholder \"password\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Verification elements of system (button)", SourceLine=27)]
        public virtual void VerificationElementsOfSystemButton()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verification elements of system (button)", ((string[])(null)));
#line 28
  this.ScenarioSetup(scenarioInfo);
#line 8
  this.FeatureBackground();
#line 29
    testRunner.Then("I see button with name \"Log in\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
