// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProfileV2Test.FeatureFiles._6
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("To sort out information in list of Students", Description="In order I can find information in list of Students\r\nAs HR\r\nI should have possibi" +
        "lity to sort out information in list of Students", SourceFile="FeatureFiles\\_6\\6.3 To sort out information in the list of Students.feature", SourceLine=5)]
    public partial class ToSortOutInformationInListOfStudentsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "6.3 To sort out information in the list of Students.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "To sort out information in list of Students", "In order I can find information in list of Students\r\nAs HR\r\nI should have possibi" +
                    "lity to sort out information in list of Students", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
#line 12
testRunner.Given("As unauthorised user I come to landing page of Profile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
testRunner.And("I log in as HR", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.And("I see page HR\'s list of students", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        public virtual void HRSortsOutInformationInTableColumns(string option, string column, string type, string sort_Order, string from_To, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HR Sorts out information in table columns", exampleTags);
#line 16
this.ScenarioSetup(scenarioInfo);
#line 11
this.FeatureBackground();
#line 17
testRunner.When(string.Format("I press \"Sort out\" button in table column \"{0}\"", column), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
testRunner.Then(string.Format("\"{0}\" information in table columns is sorted out in \"{1}\" order \"{2}\"", type, sort_Order, from_To), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option1", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option1()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option1", "Stream", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option2", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option2()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option2", "Stream", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option3", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option3()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option3", "Name rus", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option4", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option4()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option4", "Name rus", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option5", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option5()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option5", "Surname rus", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option6", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option6()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option6", "Surname rus", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option7", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option7()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option7", "Date of birth", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option8", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option8()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option8", "Date of birth", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option9", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option9()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option9", "E-mail", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option10", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option10()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option10", "E-mail", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option11", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option11()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option11", "Phone", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option12", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option12()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option12", "Phone", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option13", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option13()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option13", "Trainer", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option14", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option14()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option14", "Trainer", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option15", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option15()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option15", "Date of graduate", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option16", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option16()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option16", "Date of graduate", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option17", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option17()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option17", "Final score", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option18", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option18()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option18", "Final score", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option19", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option19()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option19", "Companies, where recommended", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option20", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option20()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option20", "Companies, where recommended", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option21", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option21()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option21", "Employer company", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option22", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option22()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option22", "Employer company", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option23", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option23()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option23", "Recommendation/employment date", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option24", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option24()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option24", "Recommendation/employment date", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option25", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option25()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option25", "Resume status", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option26", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option26()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option26", "Resume status", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option27", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option27()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option27", "Comments", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option28", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option28()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option28", "Comments", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option29", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option29()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option29", "Education", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option30", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option30()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option30", "Education", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option31", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option31()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option31", "Language", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option32", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option32()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option32", "Language", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option33", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option33()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option33", "Language level", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option34", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option34()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option34", "Language level", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option35", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option35()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option35", "Skills", "letters", "alphabetical", "A-Z", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HR Sorts out information in table columns, option36", SourceLine=20)]
        public virtual void HRSortsOutInformationInTableColumns_Option36()
        {
#line 16
this.HRSortsOutInformationInTableColumns("option36", "Skills", "numbers", "numerical", "0-9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
